name: Publish OCI image

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  push_to_registry:
    name: Push OCI image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            extra-platforms = aarch64-linux

      - uses: docker/setup-qemu-action@v3

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: raydenoir/drasl
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push OCI image
        env:
          REFERENCE: ${{ steps.meta.outputs.tags }}
        run: |
          # Build only for x86_64-linux (skip aarch64)
          NIX_BUILD_CORES=$(nproc)  # Use all CPU cores
          oci_archive="$(nix build --no-link --print-out-paths ".#oci-cross-x86_64-linux")"

          # Push directly to Docker Hub (no manifest, no compression)
          buildah push --compression none "docker-archive:$oci_archive" "docker://$REFERENCE"

